//File Name
#define filenameHack		"%s\\%d월%d일.log"		
#define filenameDebugLogin		"%s\\%d월%d일.log"
#define filenameCollectMoney	"%s\\%d월%d일.txt"
#define filenameHackLogMoney	"%s\\(돈)%d월%d일.log"
#define filenameGetHighItem		"%s\\(아이템)%d월%d일.log"
#define filenameDeleteCharacter		"%s\\(캐릭제거)%d월%d일.log"
#define filenameDeleteCharactererror	"%s\\(캐릭제거)%d월%d일.log"
#define filenameBlackUser				"%s\\(블랙유저)%d월%d일.log"
#define filenameMixItem		"%s\\(믹스쳐)%d월%d일.log"
#define filenameAgingItem		"%s\\(에이징)%d월%d일.log"
#define filenameBlessCaslte		"%s\\(블레스캐슬)%d월%d일.log"

// pluto 제련
#define filenameSmeltingItem	"%s\\(제련)%d월%d일.log"
// pluto 제작
#define filenameManufactureItem	"%s\\(제작)%d월%d일.log"
//Message
#define msg1000		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 복사아이템 ( %d )\r\n"
#define msg1010		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 창고복사아이템 ( %d )\r\n"
#define msg1011		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 창고돈 ( %d )\r\n"
#define msg1100		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 크랙핵발견 ( %s )\r\n"
#define msg1101		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 포커스변경종료 ( %s )\r\n"
#define msg1102		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트체크섬 오류 ( %d )\r\n"
#define msg1103		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 프로세스체크섬 오류 ( %d )( %s )\r\n"
#define msg1110		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리펑션코드 오류 ( %d )( %d )\r\n"
#define msg1120		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리펑션코드2 오류 ( %d )( %d )\r\n"
#define msg1130		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 펑션검사 오류 ( %d )( %d )\r\n"
#define msg1132		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 펑션검사 횟수 오류 ( %d )( %d )\r\n"
#define msg1150		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 돈초과,물약복사시도 ( %d )( %d )\r\n"
#define msg1200		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 스피드핵 ( %d )\r\n"
#define msg1250		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 시간오류-스피드핵 ( %d )( %d )\r\n"
#define msg1400		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 시간오류종료 ( %d )\r\n"
#define msg1500		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 공격비율오류 ( %d )\r\n"
#define msg1510		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 물약첵크오류 ( %d )\r\n"
#define msg1530		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 물약갯수오류 ( %d )( %d )\r\n"
#define msg1600		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 캐릭터정보저장오류 ( %d )\r\n"
#define msg1800		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 경험치획득오류 ( %d )\r\n"
#define msg1810		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 경험치획득 캐릭터오류 ( %d )\r\n"
#define msg1820		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 일반공격력오류 ( %d )\r\n"
#define msg1821		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 일반공격크기오류 ( %d )\r\n"
#define msg1823		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 연속공격오류 ( %d )\r\n"
#define msg1830		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 스킬공격력오류 ( %d )\r\n"
#define msg1833		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 스킬연속공격오류 ( %d )\r\n"
#define msg1840		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 제한구역침범 ( %d )( %d )\r\n"
#define msg1900		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 무게오류 ( %d )\r\n"
#define msg1950		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 오류아이템 ( %d )\r\n"
#define msg1960		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 복사아이템회수 ( %d ) ( %d )\r\n"
#define msg2000		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 벌칙강제종료 ( %d ) ( %d )\r\n"
#define msg2100		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 레벨급상승 ( %d ) ( %d )\r\n"
#define msg2110		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 경험치급상승 ( %d ) ( %d )\r\n"
#define msg2120		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 빠른 경험치획득 ( %d ) ( %d ) ( %d )\r\n"
#define msg2300		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 저장레벨오류 ( %d ) ( %d )\r\n"
#define msg2400		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 저장아이템오류 ( %d ) ( %d )\r\n"
#define msg2700		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 연속저장실패오류 ( %d ) ( %d )\r\n"
#define msg2800		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 계정캐릭오류 ( %s ) ( %d ) ( %d )\r\n"
#define msg4000		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 트레이드인증오류 ( %d ) ( %d )\r\n"
#define msg4100		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 돈이동오류 ( %d ) ( %d )\r\n"
#define msg5000		"%d시%d분%d초 - 동일IP과다연결 ( %d , %d )\r\n"
#define msg5100		"%d시%d분%d초 - Name:( %s %s ) / IP ( %s ) 패킷과다수신 ( %d )( %d )\r\n"
#define msg5200		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 게임서버IP오류 ( %d )( %s )\r\n"
#define msg6000		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 초기캐릭오류 ( %d )( %d )\r\n"
#define msg6100		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 레벨오류 ( %d )( %d )\r\n"
#define msg6200		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) *레벨비 경험치 이상 ( %d )( %d )\r\n"
#define msg6500		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버와 주고받은 경험치 비율 오류 ( %d )( %d ) - %d\r\n"
#define msg6510		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버와 주고받은 금액 비율 오류 ( %d )( %d ) - %d\r\n"
#define msg6600		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버와 실제 경험치 틀림 ( %dk )( %dk )\r\n"
#define msg6610		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버와 실제 돈 틀림 ( %d )( %d )\r\n"
#define msg6611		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버와 실제 돈 틀림2 ( %d )( %d )\r\n"
#define msg6612		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버와 실제 돈 틀림3 ( %d )( %d )\r\n"
#define msg6620		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 보조경험치 50% 초과 오류 ( %d )( %d )\r\n"
#define msg6630		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 경험치 오류 ( %d )/( %dk )( %dk )\r\n"
#define msg6800		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 아이템 코드 오류 ( %d )-( %d )( %d )\r\n"
#define msg6810		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 아이템 보조코드 오류 ( %d )-( %d )( %d )\r\n"
#define msg6900		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 스텟 오류 ( %d )( %d )\r\n"
#define msg6910		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 스킬포인트 오류 ( Lv %d )( SP:%d EP:%d )( QuestLog:%d )\r\n"
#define msg6920		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 무게 오류 ( %d )( %d )\r\n"
#define msg7000		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 프로세스 시간초과 ( %d )( %d )\r\n"
#define msg7010		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 인벤토리 아이템 오류 ( %d )( %d )\r\n"
#define msg7020		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 모델 오류 ( %d )( %s )( %s )\r\n"
#define msg7030		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 직업코드 오류 ( %d )/( %d )( %d )\r\n"

#define msg7100		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 공격/방어 수치 오류 ( %d )( %d )( %d )\r\n"
#define msg7110		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 에너지바 수치 오류 ( %d )( %d )( %d )\r\n"
#define msg7120		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 경험치 수신 오류 ( %d )( %d )( %d )\r\n"
#define msg7130		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 땅에서 복사아이템 발견 ( %s )( %d )( %d )\r\n"
#define msg7140		"%d시%d분%d초 - ID:( %s ) / IP ( %s ) 접근 제한 IP주소 연결시도\r\n"
#define msg7150		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 인벤토리 [아이템] 오류 ( %d )( %d )( %d )\r\n"
#define msg7160		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 인벤토리 [돈] 오류  ( %d )( %d )( %d )\r\n"

#define msg8000		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 인벤토리 [아이템] 오류  ( %d ) - ( %s )( %d )( %d / %d )\r\n"
#define msg8010		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 인벤토리 [돈] 오류  ( %d ) - ( %d )( %d )\r\n"
#define msg8020		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버간 아이템이동 코드오류  ( %d ) - ( %d )( %d )\r\n"
#define msg8030		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 저장 캐릭터 이름이 틀림  ( %s )( %s )( %s )\r\n"
#define msg8040		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 아이템 착용위치 오류  ( %d )( %d )( %d )\r\n"
#define msg8050		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s )  서버 인벤토리 사용량 초과  ( %d )( %d )( %d )\r\n"
#define msg8060		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s )  아이템 사용 코드오류  ( %d )( %d )( %d )\r\n"
#define msg8070		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 인벤토리 로딩 [복사 아이템] 발견  ( %d ) - ( %s )( %d )( %d / %d )\r\n"
#define msg8080		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리버퍼 저장오류  ( %d )( %d )( %d )\r\n"
#define msg8100		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 오토마우스 경고  ( %d )\r\n"
#define msg8102		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 매크로마우스 경고  ( %d )( %d )( %d )\r\n"
#define msg8110		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 평균공격력(방어) 비율 경고 ( %d )( %d )/( %d )\r\n"
#define msg8120		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 평균공격력(공격) 비율 경고 ( %d )( %d )/( %d )\r\n"
#define msg8130		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) nSPRITE 연결종료 ( %d )( %d )\r\n"
#define msg8140		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) nSPRITE 유효시간 초과 ( %d )( %d )\r\n"
#define msg8200		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 인벤토리 [에이징] 오류 [쉘텀] ( %d )-( %d / %d )\r\n"
#define msg8210		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 인벤토리 [에이징] 오류 ( %d )-( %d / %d )( %d / %d )\r\n"
#define msg8300		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 재연결( %d )\r\n"
#define msg8400		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버 인벤토리 데이타 확인[연결종료]( %d )( %d )\r\n"
#define msg8500		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 데미지 패킷 암호화 오류( %d )( %d )( %d )\r\n"
#define msg8510		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 데미지 제한치 초과( %d )( %d %d %d )( %d %d %d )\r\n"
#define msg8520		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 모션속도 경고 ( %d )\r\n"
#define msg8530		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 공격스킬 경고 ( %d )\r\n"
#define msg8540		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 스킬조작 경고 ( %d )( %d )\r\n"
#define msg8550		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 스킬조작 경고2 ( %d )( %d )( %d )\r\n"
#define msg8560		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 레벨초기화 [32비트 경험치오류] ( %d )( %d )\r\n"
#define msg8570		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 과도한 캐릭정보 업데이트 ( %d  %d )( %d )\r\n"
#define msg8580		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클라이언트 데미지 패킷오류 ( %d )( %d )\r\n"
#define msg8600		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 무적모드 경고 ( %d )( %d )\r\n"
#define msg8700		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 게임가드 연결종료( %d )( %d )\r\n"
#define msg8710		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 게임가드 유효시간 초과( %d )( %d )\r\n"
#define msg8720		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 수상한 모듈 발견( %s )( %d )\r\n"
#define msg8730		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 속성 오류( %d )( %d )( %d )\r\n"
#define msg8800		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버물약 갯수 오류 ( %d )( %d )( %d )\r\n"
#define msg8810		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서버물약 갯수 이동 오류 ( [%d]  %d )/( %d )\r\n"
#define msg8820		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 레벨퀘스트 조작 경고 ( %d )( %d )\r\n"
#define msg8830		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 상점 위조 아이템 발견 (ItemCode: %d )(Price: %d )\r\n"
#define msg8840		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) *서버 돈 수치오류  ( %d ) - ( %s ) (%d)(%d) = (%d)\r\n"
#define msg8850		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 스킬 사용레벨 오류 ( Lv:%d )( Code:%d )\r\n"
#define msg8860		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 필드지형 확인 오류 Area([%d] X=%d Y=%d Z=%d) SubHeight(%d)\r\n"
#define msg8870		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 클랜코드 비교 오류 ClanCode( %d <> %d ) ClanMaster(%d)\r\n"
#define msg8880		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 모델파일 오류 ( %s )( %s )\r\n"
#define msg8890		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터 재로딩 시도 ( %s )( %s )( %d )\r\n"
#define msg8900		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 필드NPC기능 경고 ( Field: %d )( %d )\r\n"
#define msg8910		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 아이템메쉬 오류 ( %d )( %d )\r\n"
#define msg8920		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 불법서버 침입시도\r\n" 

#define msg10000	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리기록이름 오류1 ( %s )( %s )\r\n"
#define msg10001	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리기록이름 오류2 ( %s )( %s )\r\n"
#define msg10002	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리기록이름 오류3 ( %s )( %s )\r\n"
#define msg10003	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리기록이름 오류4 ( %s )( %s )\r\n"
#define msg10005	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 메모리기록 오류5 ( %s )( %s )\r\n"
#define msg10006	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 초기기록메모리 오류 ( %s )( %s )\r\n"
#define msg10007	"%d시%d분%d초 - 기록버퍼 포인트오류 /IP ( %s ) / ( %d )( %d )\r\n"
#define msg10010	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 캐릭터계정 불일치  ( %s )\r\n"
#define msg10020	"%d시%d분%d초 - ID:( %s ) / IP ( %s ) 인증오류 ( %s  %s )\r\n" 
#define msg11000	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 서비스종료 요구\r\n"

#define msg21000	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 이벤트 고득점 ( %d )( %d )\r\n"

#define msgHack		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 해킹경고 ( %d )\r\n"
#define msgHack100	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 해킹경고 ( %d ) - 흡수력( %d ) 공격력( %d ) 방어력( %d )\r\n"
#define msgDebugloginID		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 디버그접속 ( %d )\r\n"
#define msgDebugloginIP		"%d시%d분%d초 - Name:( %s ) / IP ( %s ) 디버그접속 ( %d )\r\n"
#define msgKindPeople		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) 불우이웃기부금 ( %d 원 ) 금일누적합계( %d 원 )\r\n"
#define msgHackMoney		"%d시%d분%d초 - Name:( %s ) 레벨( %d ) 소지금액 ( %d )\r\n"
#define	msgHighItem		"%d시%d분%d초 - Name:( %s ) 레벨( %d ) 아이템( %s ) 코드( %d ) 고유번호( %d %d ) 특화코드( %d ) 신규( %d )\r\n"
#define msgCharDelete1		"%d시%d분%d초 - ID( %s ) Name( %s ) IP( %s ) 레벨( %d ) 경험치( %d ) 소지금액 ( %d )\r\n"
#define msgCharDelete2		"%d시%d분%d초 - ID( %s ) Name( %s ) 오류캐릭터\r\n"
#define msgMixItem			"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 아이템( %s ) ( %d %d <%d> ) -> ( %d %d <%d> )\r\n"
// pluto 제련
#define msgSmeltingItem		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 아이템( %s ) ( %d %d <%d> )\r\n"
// pluto 제작
#define msgManufactureItem		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 아이템( %s ) ( %d %d <%d> )\r\n"

#define msgAgingItem		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 아이템     ( %s ) [%d] ( %d %d <%d> ) -> ( %d %d <%d> )\r\n"
#define msgAgingUpItem		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 에이징업   ( %s ) [%d] ( %d %d <%d> ) -> ( %d %d <%d> )\r\n"
#define msgAgingFailItem	"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 에이징실패 ( %s ) [%d] ( %d %d <%d> )\r\n"

#define msgBlackUser		"%d시%d분%d초 - ID( %s ) - 거부시간( %d )\r\n"

